# Run tests, build wheel, and if this is a tagged commit
# beginning with v then deploy to pypi (pypi test for now).

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip wheel twine setuptools_scm
    pip install numpy
  displayName: 'Install dependencies'

- script: |
    git clone --depth 1 https://github.com/xdf-modules/example-files.git
  displayName: 'Download test data'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Test'

- script: |
    python setup.py sdist bdist_wheel
  displayName: 'Build wheel'

- task: TwineAuthenticate@0
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
  inputs:
    externalSources: '5ba26794-ed5b-43b0-8414-7bb1416ec0ad'  # -r pypi
#    externalSources: '025cb3c4-642b-4fac-829c-fe8634f1a504'  # -r testpypi

- script: 'python -m twine upload -r pypi --config-file $(PYPIRC_PATH) --skip-existing dist/*'
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
  displayName: 'Deploy to PyPI'

